# These are supported funding model platforms

github: tarsislimadev
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:
custom: ["https://www.paypal.com/donate?campaign_id=4U33HDLMV6TBE", "https://link.mercadopago.com.br/brtmvdl"]
